services:
    Github\Client:
        class: Github\Client
        calls:
            - method: authenticate
              arguments:
                  - '%env(GITHUB_USERNAME)%'
                  - '%env(GITHUB_SECRET)%'
                  - '%env(GITHUB_AUTH_METHOD)%'
            - method: addCache
              arguments:
                  - '@Cache\Adapter\Predis\PredisCachePool'

    Github\ResultPager:
        arguments:
          - '@Github\Client'
