home:
    path: /
    controller: App\Controller\HomeController::index

snippet_all:
    path: /snippet/all/
    defaults: { _controller: 'App\Controller\SnippetController::all' }

pugx_badge_packagist:
    path: /packages/{repository}
    host: "packagist.org"
    schemes:  [https]
    requirements:
      repository: "[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+"

search_packagist:
    path: /search_packagist
    controller: App\Controller\PackagistController::search
    methods:  [GET]
